using SQLite4Unity3d;

/// <summary>
/// LLMLogEntry represents a single logged interaction with the LLM visual analysis system.
/// 
/// This class is used both as a data transfer object and as the SQLite table schema.
/// SQLite4Unity3d automatically creates a table based on this class's properties,
/// with the property names becoming column names.
/// 
/// Each log entry captures the complete context of an LLM interaction:
/// - Session information (for grouping related interactions)
/// - Object information (what the user looked at)
/// - Physical properties (quantitative data about the object)
/// - AI responses (both visual and text LLM outputs)
/// - Timestamp (when the interaction occurred)
/// 
/// Research Use Cases:
/// - Analyzing which objects users interact with most
/// - Evaluating LLM response quality
/// - Understanding user behavior patterns
/// - A/B testing different prompts or models
/// - Building training datasets for custom models
/// 
/// Table Schema (auto-generated by SQLite4Unity3d):
/// CREATE TABLE LLMLogEntry (
///     id INTEGER PRIMARY KEY AUTOINCREMENT,
///     sessionId INTEGER,
///     objectName TEXT,
///     area REAL,
///     volume REAL,
///     visualInsight TEXT,
///     llmReply TEXT,
///     timestamp TEXT
/// )
/// </summary>
public class LLMLogEntry
{
    /// <summary>
    /// Unique identifier for this log entry.
    /// Automatically assigned by SQLite using auto-increment.
    /// 
    /// The PrimaryKey attribute marks this as the table's primary key.
    /// The AutoIncrement attribute means SQLite assigns values automatically.
    /// </summary>
    [PrimaryKey, AutoIncrement]
    public int id { get; set; }

    /// <summary>
    /// Session identifier for grouping related interactions.
    /// 
    /// All log entries within a single play session share the same sessionId.
    /// This allows filtering and analyzing data by session for:
    /// - Per-session analytics
    /// - User journey analysis
    /// - Comparing behavior across sessions
    /// 
    /// Session IDs are managed by SessionManager and increment each play session.
    /// </summary>
    public int sessionId { get; set; }

    /// <summary>
    /// Name of the GameObject that was analyzed.
    /// Taken from the GameObject's name property in Unity.
    /// 
    /// This often contains useful information like product names,
    /// category codes, or asset identifiers that can be used for
    /// aggregating data across similar objects.
    /// </summary>
    public string objectName { get; set; }

    /// <summary>
    /// Approximate surface area of the object in square meters.
    /// Calculated from the object's bounding box.
    /// 
    /// Useful for:
    /// - Categorizing objects by size
    /// - Correlating size with interaction frequency
    /// - Validating physical plausibility of LLM responses
    /// </summary>
    public float area { get; set; }

    /// <summary>
    /// Approximate volume of the object in cubic meters.
    /// Calculated from the object's bounding box.
    /// 
    /// Combined with surface area, provides dimensional context
    /// for the LLM analysis and for post-hoc data analysis.
    /// </summary>
    public float volume { get; set; }

    /// <summary>
    /// Raw output from the visual analysis stage (vision LLM).
    /// Contains the first-stage description of what the image shows.
    /// 
    /// This is the intermediate result before being combined with
    /// physical data and sent to the text LLM for final processing.
    /// Stored for debugging and comparing different vision models.
    /// </summary>
    public string visualInsight { get; set; }

    /// <summary>
    /// Final response from the text LLM.
    /// This is what was displayed to the user in the UI panel.
    /// 
    /// Combines information from both the visual insight and
    /// physical properties to provide a comprehensive description.
    /// </summary>
    public string llmReply { get; set; }

    /// <summary>
    /// ISO 8601 formatted timestamp of when the interaction occurred.
    /// Format: yyyy-MM-ddTHH:mm:ss.fffffffZ (e.g., "2024-01-15T14:30:00.0000000Z")
    /// 
    /// Stored as text for portability across database systems.
    /// Can be parsed back to DateTime using DateTime.Parse().
    /// 
    /// Uses UTC time to avoid timezone ambiguity.
    /// </summary>
    public string timestamp { get; set; }
}
